version: '3.8'

services:
  # Serviço do SQL Server
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql-server-container
    environment:
      SA_PASSWORD: Docker1206
      ACCEPT_EULA: Y
      MSSQL_DBNAME: investment_portfolio
    ports:
      - "1433:1433"
    networks:
      - my-network

networks:
  my-network:
